define(function() {
	return {
		pos: {type: 'posvector'},
		posVar: {type: 'posvector'},
		life: {type: 'unsignednumber', params: [0,10,0.1]},
		lifeVar: {type: 'unsignednumber', params: [0,10,0.1]},
		totalParticles: {type: 'unsignednumber'},
		emissionRate: {type: 'unsignednumber'},
		startColor: {type: 'color'},
		startColorVar: {type: 'color'},
		endColor: {type: 'color'},
		endColorVar: {type: 'color'},
		radius: {type: 'unsignednumber'},
		radiusVar: {type: 'unsignednumber'},
		texture: {type: 'texture'},
		textureSource: {type: 'string'},
		vfSource: {type: 'string'},
		textureEnabled: {type: 'boolean'},
		renderMode: {type: 'renderModePicker'},
		speed: {type: 'unsignednumber'},
		speedVar: {type: 'unsignednumber'},
		angle: {type: 'number'},
		angleVar: {type: 'unsignednumber'},
		gravity: {type: 'vector'},
		radialAccel: {type: 'number'},
		radialAccelVar: {type: 'unsignednumber'},
		tangentialAccel: {type: 'number'},
		tangentialAccelVar: {type: 'unsignednumber'},
		startScale: {type: 'unsignednumber', params: [0,10,0.1]},
		startScaleVar: {type: 'unsignednumber', params: [0,10,0.1]},
		endScale: {type: 'unsignednumber', params: [0,10,0.1]},
		endScaleVar: {type: 'unsignednumber', params: [0,10,0.1]},
		splineAnchorPts: {type: 'pointlist'},
		splineIsPath: {type: 'boolean'},
		splineClockwise: {type: 'boolean'},
		splineSpeed: {type: 'unsignednumber'},
		splineRelForceOn: {type: 'boolean'},
		startDelay: {type: 'unsignednumber'},
		rotationSpeed: {type: 'number', params:[-100,100]},
		rotationSpeedVar: {type: 'unsignednumber', params: [0,100]},
		actsOn: {type: 'actsOn'}
	};
});

